---
title: "cometh_hw3b"
output:
  word_document: default
  html_document: default
---

#Q1
```{r}
p <- 0.4
k <- 3
n.repeat <- 1000 #1000번의 시행
peaks <- rep(0,n.repeat) 
for(r in 1:n.repeat){
  balance <- k #초기치 잔액
  peak <- 3 #3
  while(balance>0){ #잔액이 0보다 크면 trial 가능 아니면 X
    balance <- balance+2*rbinom(1,1,p)-1 #p=1 승리 k+1/p=0 k-1 
    if(balance>=peak){peak <- balance #balance하나가 최신화되어서 나올 때 마다 
    }  #peak보다 크면 peak 교체 그렇지 않으면 peak를 유지
  }
  peaks[r] <- peak #1000번 반복 중 r번째에서의 peak를 peaks[r]에 할당
}
summary(peaks)
library(descr)
freq(peaks, plot=T) #library(descr) 분포표와 히스토그램
```

peak는 한 번 시뮬레이션할 때 max(balance) 값이므로 조건문을 통해서 초기 설정된 peak와 한 번 gambling을 수행할 떄의balance값의 비교를 통해 최신화 하고 1회의 시뮬레이션이 끝날 때(=balance=<0) peak에 저장된 값을 peaks[r]에 할당한다. 

#Q2
2.1)
```{r}
logis=rlogis(1000,0,scale= 0.5) #logistic dist(0,0.5)를 따르는 난수 1000개 생성
hist(logis, main = "freqency of logistic(0,0.5)", xlab = "x") 
```

2.2)
```{r}
m=0;s=0.5
u <- runif(1000) #unif분포로 logistic dist를 표현해야하므로 일단 1000개의 ~unif(0,1)인 난수를 생성 
x <- m-s*log((1/u)-1) #주어진 CDF가 Unif(0,1)을 따른다는 것이 주어졌으므로 이를 X에 대해 풀어서 X의 값을 얻음 
hist(x, nclass = 20)  
```

$F(x)=U\sim Uniform(0,1)$이므로 $F(x)=\frac{1}{1+e^{\frac{-(x-m)}{s}}}=U$이다. 그리고 이를 x에 대하여 풀어서 쓰면
$x=m-s\log(\frac{1}{U}-1)$이다. 따라서 unif(0,1)을 따르는 1000개의 난수이용해 x를 구해서 히스토그램을 그리면 로지스틱 분포의 히스토그램과 유사한 bell-shape의 그림이 그려짐을 확인할 수 있다.